# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  kon_config = debug
  testing_config = debug
  runtime_config = debug
endif
ifeq ($(config),release)
  GLFW_config = release
  kon_config = release
  testing_config = release
  runtime_config = release
endif

PROJECTS := GLFW kon testing runtime

.PHONY: all clean help $(PROJECTS) Core Dependencies Tools

all: $(PROJECTS)

Core: kon

Dependencies: GLFW

Tools: runtime testing

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C external/glfw -f Makefile config=$(GLFW_config)
endif

kon: GLFW
ifneq (,$(kon_config))
	@echo "==== Building kon ($(kon_config)) ===="
	@${MAKE} --no-print-directory -C kon -f Makefile config=$(kon_config)
endif

testing: kon
ifneq (,$(testing_config))
	@echo "==== Building testing ($(testing_config)) ===="
	@${MAKE} --no-print-directory -C testing -f Makefile config=$(testing_config)
endif

runtime: kon GLFW
ifneq (,$(runtime_config))
	@echo "==== Building runtime ($(runtime_config)) ===="
	@${MAKE} --no-print-directory -C runtime -f Makefile config=$(runtime_config)
endif

clean:
	@${MAKE} --no-print-directory -C external/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C kon -f Makefile clean
	@${MAKE} --no-print-directory -C testing -f Makefile clean
	@${MAKE} --no-print-directory -C runtime -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   kon"
	@echo "   testing"
	@echo "   runtime"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"